package com.wora.easyOrder.util.apiResponse.fail;

public enum FailType {
    DUPLICATE_FX_DEAL_ID,
    BAD_REQUEST,
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    HTTP_MESSAGE_NOT_READABLE,
    CONSTRAINT_VIOLATION_ERROR,
    AUTHENTICATION_ERROR,
    AUTHORIZATION_ERROR,
}
